---
title: "New_Data_EDA"
author: "Liz Miller"
date: "7/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EDA with the 2019 Data!! Thank you Sean :)  

I'm going to put things I find at the top here and add to it as I work through code and graphs below:

1. IC_CENTER, BUDGET_START_DATE, BUDGET_END_DATE, and FY_TOTAL_COST_SUBPROJECT are all entirely NA
2. FY.x and FY.y are slightly different. 

```{r importing the datat, message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytext)
library(readr)
library(naniar)

raw_abstracts_2020 <- read_csv("~/git/dspg20rnd/dspg20RnD/data/original/working_federal_reporter_2020.csv")

abstracts_2019 <- raw_abstracts_2020 %>%
  filter(FY.y == 2019)

```

## What kind of missing values do we have?

```{r show missing values, echo = FALSE}

sum(is.na(raw_abstracts_2020$IC_CENTER))
gg_miss_var(raw_abstracts_2020, show_pct = TRUE) +
  labs(y = "% Missing: All")

gg_miss_var(abstracts_2019, show_pct = TRUE) +
  labs(y = "# Missing: 2019")
```

```{r convert the data to a tiny format for some word based analysis, echo = FALSE}

tidy_all <- tibble(text = raw_abstracts_2020$ABSTRACT)
tidy_2019 <- tibble(text = abstracts_2019$ABSTRACT)
tidy_titles <- tibble(text = raw_abstracts_2020$PROJECT_TITLE)

tidy_all <- tidy_all %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

tidy_2019 <- tidy_2019 %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

tidy_titles <- tidy_titles %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE)

tidy_2019 %>%
  filter(n > 30000) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Words: 2019 Abstracts")

tidy_all %>%
  count(word, sort = TRUE) %>%
  filter(n > 500000) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Words: All Abstracts")

tidy_titles %>%
  count(word, sort = TRUE) %>%
  filter(n > 20000) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  ggtitle("Titles: All Abstracts")

```

##MORE THINGS

``` {r variable counts}

raw_abstracts_2020 %>%
  filter(FY.x < 2020) %>%
  filter(FY_TOTAL_COST < 2000000)
  ggplot(aes(FY_TOTAL_COST)) +
  geom_bar()

```

##

``` {r code}

raw_abstracts_2020$ab_char <- nchar(raw_abstracts_2020$ABSTRACT)

raw_abstracts_2020 %>%
  ggplot(aes(x = ab_char, colour = DEPARTMENT)) +
  geom_freqpoly(bins = 10)

raw_abstracts_2020 %>%
  ggplot() +
  stat_summary(aes(x = DEPARTMENT, y = ab_char),
               fun.ymin = min,
               fun.ymax = max,
               fun.y = mean)
```


